apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-push-bind
spec:
  params:
  - name: repo-url
    value: $(body.repository.clone_url)
  - name: image-reference
    value: bonnce/$(body.repository.name):$(extensions.docker_version)
  - name: trigger-body
    value: $(extensions.branch_name)