apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: manifest-clone-push
spec:
  description: | 
    This pipeline clones a git repo, then echoes the README file to the stdout.
  params:
  - name: script
    type: string
  - name: git-user
    type: string
  - name: git-email
    type: string
  - name: repo-url
    type: string
    description: The git repo URL to clone from.
  workspaces:
  - name: shared-data
    description: | 
      This workspace contains the cloned repo files, so they can be read by the
      next task.
  tasks:
  - name: fetch-source-manifest
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
  - name: build-push
    runAfter: ["fetch-source-manifest"]
    taskRef:
      name: git-cli
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: GIT_SCRIPT
      value: $(params.script)
    - name: GIT_USER_NAME
      value: $(params.git-user)
    - name: GIT_USER_EMAIL
      value: $(params.git-email)