apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-build-run-
spec:
  pipelineRef:
    name: clone-build-push
  podTemplate:
    securityContext:
      fsGroup: 65532
  serviceAccountName: git-ssh-bot
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: docker-credentials
    secret:
      secretName: docker-credentials
  params:
  - name: repo-url
    value: git@github.com:bonnce/node-source-manifest.git
  - name: git-user
    value: bonnce
  - name: git-email
    value: bonce_reloko@hotmail.com
  - name: findInFile
    value: "image:.*"
  - name: image-reference
    value: "image: bonnce/node-source"
  - name: file-name-replace
    value: deployment.yaml
  - name: commit-message
    value: "image update"
  - name: files-added-count
    value: "2"
  - name: files-modified-count
    value: "4"