apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: modify-manifest
spec:
  steps:
    - name: modify and push
      workingDir: $(workspaces.source.path)
      image: ubuntu 
      script: |
        #!/bin/sh
        git remote add origin
        sed -ire 's/image:.*/image: $(params.image_reference)/i' deployment.yaml
        rm -f deployment.yamlre
        git add .
        git commit -m 'image change $(params.image_reference)'
        git push
  workspaces:
    - description: Holds the context and Dockerfile
      name: source